AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - db/**/*
    - Guardfile
    - spec/**/*
    - vendor/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true

# Bundler

# Gemspec

# Layout
Layout/BeginEndAlignment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 140
  Severity: refactor

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true


# Lint
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true


# Metrics
Metrics/AbcSize:
  Max: 20
  Severity: refactor

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10
  Severity: refactor

Metrics/MethodLength:
  Max: 20
  Severity: refactor

Metrics/PerceivedComplexity:
  Max: 10
  Severity: refactor


# Migration

# Naming
Naming/MemoizedInstanceVariableName:
  Enabled: false

# Security

# Style
Style/AccessorGrouping:
  Enabled: true

Style/Alias:
  Enabled: false

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/CombinableLoops:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/WordArray:
  Enabled: false
